tools/importer/import.js
Fix #9 
Test URLs:
- After: https://import-script--accenture-newsroom--hlxsites.hlx.page/
=> feat: import script

blocks/newslist/newslist.js
Fix Newlist description extraction logic
Test URLs:
- After: https://newslist-fixes2--accenture-newsroom--hlxsites.hlx.page/
=> fix: newslist description extraction update

tools/importer/import.js
- add contacts from right rail to main content (for older articles)
- convert title to h1
- add section after abstract (for old and new articles)
Fix #27
=> Import updates

blocks/header/header.css, blocks/hero/hero.css, blocks/hero/hero.js, blocks/newslist/newslist.css, blocks/newslist/newslist.js, scripts/scripts.js, styles/styles.css
Fix #19 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/subjects/technology
- After: https://hero--accenture-newsroom--hlxsites.hlx.page/subjects/technology
- After: https://hero--accenture-newsroom--hlxsites.hlx.page/industries/systems-integration-technology
- After: https://hero--accenture-newsroom--hlxsites.hlx.page/news/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
=> feat: hero block for search, category and article pages

blocks/hero/hero.css, blocks/newslist/newslist.js, scripts/scripts.js, styles/styles.css
Fix #4 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
- After: https://article-styling--accenture-newsroom--hlxsites.hlx.page/news/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
=> fix: article page styling

scripts/scripts.js
Fix - Skip internal paths from searching
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/search?q=tech&page=12
- After: https://search-fixes--accenture-newsroom--hlxsites.hlx.live/search?q=tech&page=12
=> fix: skip internal paths from searching

blocks/aside/aside.js, blocks/newslist/newslist.js, scripts/scripts.js, styles/styles.css
Fix Aside and date issues
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
- After: https://aside-fixes--accenture-newsroom--hlxsites.hlx.page/news/2023/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
=> fix: aside, date issues

blocks/header/header.css, blocks/home-hero/home-hero.css, blocks/home-hero/home-hero.js, blocks/newslist/newslist.css
Fix #26 
Test URLs:
- After: https://home-hero--accenture-newsroom--hlxsites.hlx.page/
=> feat: home hero block

tools/importer/import.js
Fix #34 
Test URLs:
- After: https://import-updates2--accenture-newsroom--hlxsites.hlx.page/
=> fix: importer fixes

blocks/aside/aside.js, blocks/footer/footer.css, blocks/footer/footer.js, blocks/header/header.js, blocks/hero/hero.js, blocks/home-hero/home-hero.js, blocks/newslist/newslist.js, scripts/constants.js, scripts/scripts.js
Fix #39 
Test URLs:
- After: https://link-annotation--accenture-newsroom--hlxsites.hlx.live/
- After: https://link-annotation--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-optimind
=> Link annotation

blocks/home-hero/home-hero.js
Fix #42 
Test URLs:
- After: https://home-hero-webp--accenture-newsroom--hlxsites.hlx.live/
=> Home hero webp

scripts/delayed.js
Fix : Loading staging scripts for Adobe launch for validation.
Test URLs:
- After: https://martech-stage--accenture-newsroom--hlxsites.hlx.page/
=> fix: loading staging script for martech

helix-query.yaml
Fix Adding template to query index
Test URLs:
- After: https://query-index-updates--accenture-newsroom--hlxsites.hlx.page/
=> fix: adding template to query index

scripts/delayed.js
Fix #76 
Test URLs:
- After: https://launch-staging--accenture-newsroom--hlxsites.hlx.page/
=> fix: Updating launch staging script

blocks/newslist/newslist.css, blocks/newslist/newslist.js, scripts/ffetch.js, scripts/scripts.js
Fix #45 
Test URLs:
- After: https://listing-count--accenture-newsroom--hlxsites.hlx.live/
- After: https://listing-count--accenture-newsroom--hlxsites.hlx.live/?page=235
- After: https://listing-count--accenture-newsroom--hlxsites.hlx.live/industries/corporate-citizenship-diversity
- After: https://listing-count--accenture-newsroom--hlxsites.hlx.live/industries/corporate-citizenship-diversity?page=2
- After: https://listing-count--accenture-newsroom--hlxsites.hlx.live/search?q=technology
- After: https://listing-count--accenture-newsroom--hlxsites.hlx.live/news/2018/accenture-to-host …
=> feat: using ffetch to show listing pages

blocks/footer/footer.css
Fix # 
- https://github.com/hlxsites/accenture-newsroom/issues/73
Test URLs:
- After: https://59840-scroll-bar-issue--accenture-newsroom--hlxsites.hlx.page/
=> fix: remove horizontal scroll caused by footer width

blocks/aside/aside.css, blocks/aside/aside.js
Fix #59 #79 #99 #110 
Test URLs:
- After: https://78385---posting-sharetools--accenture-newsroom--hlxsites.hlx.page/
(#59 has been fixed already)
=> Fix: Share Tools Font Size + Margin + Tooltip

blocks/newslist/newslist.css, blocks/newslist/newslist.js
Fix #93 #94 #109 
Test URLs:
- After: https://73340-search-module--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Search Focus Highlight and Cursor + Tooltips + Link Target

blocks/home-hero/home-hero.css
Fix # 
- https://github.com/hlxsites/accenture-newsroom/issues/57
Test URLs:
- After: https://60344-Multinav--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Add on hover color for the Home Hero multinav links

blocks/aside/aside.css
Fix #75 
Test URLs:
- After: https://66086-News-Post-Tags--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Bottom spacing in tags

blocks/footer/footer.js
Fix #
- https://github.com/hlxsites/accenture-newsroom/issues/100
Test URLs:
- After: https://59574-Footer-Icon--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Add title attribute for the Footer Social Media Icons

blocks/newslist/newslist.css
Fix #50 
- https://github.com/hlxsites/accenture-newsroom/issues/50
Test URLs:
- After: https://59857-Pagination--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Update media query min-width to 768px tablet viewport

scripts/delayed.js
Fix #74 
Test URLs:
- After: https://datamodel--accenture-newsroom--hlxsites.hlx.page/
=> feat: adding data model for analytics tracking

404.html, blocks/hero/hero.js, blocks/newslist/newslist.css, blocks/newslist/newslist.js, scripts/scripts.js, styles/styles.css
Fix #128 
Test URLs:
- After: https://404--accenture-newsroom--hlxsites.hlx.page/
=> feat: 404 page implementation

blocks/hero/hero.css, styles/styles.css
Fix #68 
Fix #67 
fix #54 
Test URLs:
- After: https://59214-news-posting--accenture-newsroom--hlxsites.hlx.page/
=> fix breadcrumb alignment

blocks/header/header.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/47
- https://github.com/hlxsites/accenture-newsroom/issues/47
Test URLs:
- After: https://59650-nav-label--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Add toggle of level two label

blocks/footer/footer.css, blocks/footer/footer.js
Fix #153
Fix #98 
Test URLs:
- After: https://86330-global-footer-social-media--accenture-newsroom--hlxsites.hlx.page/
=> Fix: link target and spacing fix

blocks/video/video.css, blocks/video/video.js
Fix #150 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/drafts/ravi/accenture-song-wins-dan-wieden-titanium-grand-prix-for-tuvalu-the-first-digital-nation
- After: https://video--accenture-newsroom--hlxsites.hlx.page/drafts/ravi/accenture-song-wins-dan-wieden-titanium-grand-prix-for-tuvalu-the-first-digital-nation
=> feat: video block

blocks/hero/hero.css, blocks/hero/hero.js
Fix #131 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/earnings-infographics
- After: https://hero-updates--accenture-newsroom--hlxsites.hlx.live/earnings-infographics
=> fix: showing title in hero

blocks/newslist/newslist.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/52
- https://github.com/hlxsites/accenture-newsroom/issues/52
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/?from_date=7/26/2023&to_date=7/27/2023
- After: https://59782-date-filter--accenture-newsroom--hlxsites.hlx.live/?from_date=7/26/2023&to_date=7/27/2023
=> Fix: Add checks if the "date" and "to" is the same date for date filter

blocks/newslist/newslist.css
Fix:
-  https://github.com/hlxsites/accenture-newsroom/issues/72
-  https://github.com/hlxsites/accenture-newsroom/issues/78
-  https://github.com/hlxsites/accenture-newsroom/issues/71
Test URLs:
- After: https://59834--news-card-font-size--accenture-newsroom--hlxsites.hlx.page/
=> fix newsfeed spacing and font size issue

blocks/aside/aside.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/133
- https://github.com/hlxsites/accenture-newsroom/issues/133https://github.com/hlxsites/accenture-newsroom/issues/133
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-completes-acquisition-of-anser-advisory
- After: https://84836-revert-pdf--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-completes-acquisition-of-anser-advisory
=> Fix: Revert PDF links

blocks/aside/aside.css, styles/styles.css
Fix 
#162
#81 
#129 
Test URLs:
- After: https://67485-news-posting-article--accenture-newsroom--hlxsites.hlx.page/
=> fix aside component in table and mobile

blocks/newslist/newslist.js
Fix #166 
Test URLs:
- After: https://newslist-fix--accenture-newsroom--hlxsites.hlx.live/
=> fix: avoiding the reading from undefined in matchingParagraph

blocks/newslist/newslist.js
Fix #168 
Test URLs:
- After: https://newslist-empty-tiles--accenture-newsroom--hlxsites.hlx.live/
=> fix: empty tiles in news list and also limit the description to 800 characters

404.html, blocks/aside/aside.js, blocks/hero/hero.js, blocks/newslist/newslist.js, scripts/delayed.js, scripts/scripts.js
Fix #148
Test URLs:
- After: https://placeholders--accenture-newsroom--hlxsites.hlx.live/
- After: https://placeholders--accenture-newsroom--hlxsites.hlx.live/subjects/technology
=> feat: implementing placeholders feature for languages

blocks/newslist/newslist.css
**Fix** 
#72
Note: I forgot to include the iPod Pro in checking the font size. 
Test URLs:
- After: https://59834-news-card--accenture-newsroom--hlxsites.hlx.page/
=> fix font in tablet view

blocks/newslist/newslist.css, styles/styles.css
Fix 
#171 
#172 
#152 
Test URLs:
- After: https://99354-aside-component--accenture-newsroom--hlxsites.hlx.page/
=> fix aside component padding

blocks/header/header.js
Fix #123 
Test URLs:
- After: https://header-annotations--accenture-newsroom--hlxsites.hlx.live/
=> fix: adding data attributes on primary nav component

scripts/delayed.js
Fix #183
Test URLs:
- After: https://analytics-issues--accenture-newsroom--hlxsites.hlx.page/
=> fix: intermittent loading of launch script

scripts/delayed.js
Fix #183 
Test URLs:
- After: https://analytics-issues--accenture-newsroom--hlxsites.hlx.page/
=> fix: changing the order of one trust to before the martech

blocks/newslist/newslist.js
Fix #178 
Test URLs:
- After: https://newslist-description--accenture-newsroom--hlxsites.hlx.live/
- After: https://newslist-description--accenture-newsroom--hlxsites.hlx.live/subjects/technology
=> fix: wrapping in div tag to close the unclosed tags in description

blocks/header/header.css, blocks/header/header.js
Fix #65 
Fix #66 
Test URLs:
- After: https://59628-global-header-texts--accenture-newsroom--hlxsites.hlx.page/
=> Fix: global header text bold and wrap

blocks/newslist/newslist.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/125
- https://github.com/hlxsites/accenture-newsroom/issues/125
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/search?q=accenture
- After: https://1097183-search--accenture-newsroom--hlxsites.hlx.page/search?q=accenture
=> Fix: Add condition for analytics value of search title result

scripts/delayed.js, scripts/one-trust-geo-script.js, scripts/scripts.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/156
- https://github.com/hlxsites/accenture-newsroom/issues/156
Test URLs:
- After: https://156-geo-script--accenture-newsroom--hlxsites.hlx.page/
Added the script needed as per mentioned on the issue
=> 156 geo script

blocks/hero/hero.css, blocks/newslist/newslist.css
Fix search hero padding and view in small viewport.
Fix 
#95 
Test URLs:
- After: https://73355-search-view--accenture-newsroom--hlxsites.hlx.page/
=> fix search hero padding

blocks/newslist/newslist.js
Fix #225
Test URLs:
**Issue#1 : Reflected Cross Site Scripting (XSS)**
- Before:
**1.** https://main--accenture-newsroom--hlxsites.hlx.live/search?q=%3Chtml%3E+%3Ca+href%3D%23+onmouseover%3D%22alert(%27Hey.%20I%20got%20an%20vulnerbility%27)%22%3EThis+is+test+%3C%2Fa
**2.** https://main--accenture-newsroom--hlxsites.hlx.live/search?q=--%21%3E%3Cimg+src%3D1+onerror%3Dalert%28%60XSS%60%29%3E
- After: 
**1**. https://225-xss-issue--accenture-newsroom--hlxsites.hlx.live/search?q=%3Chtml%3E+%3Ca+href%3D%23+onmouseover%3D%22alert(%27Hey.%20I%20got%20an%20vulnerbility%27)%22%3EThis+is+test+%3C%2Fa
**2.** …
=> [FIX] - XSS, CSS and HTML Injection

scripts/scripts.js, styles/styles.css
Fix https://github.com/hlxsites/accenture-newsroom/issues/69
- https://github.com/hlxsites/accenture-newsroom/issues/69
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
- After: https://60633-content--accenture-newsroom--hlxsites.hlx.page/news/2023/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
=> Fix: aligned center the Article divider # # #

blocks/header/header.css
Fix #65 
Test URLs:
- After: https://60434-third-level-nav--accenture-newsroom--hlxsites.hlx.live/
=> Fix: third level nav

blocks/newslist/newslist.js, scripts/scripts.js
Fix #239 
Test URLs:
- After: https://149669-newsfeed-date--accenture-newsroom--hlxsites.hlx.page/
=> 149669 newsfeed date

blocks/newslist/newslist.js, scripts/scripts.js
Fix #185 #188 
Test URLs: bug 185
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/subjects/analytics
- After: https://100434-100726-calendar-update--accenture-newsroom--hlxsites.hlx.live/subjects/analytics
Test URLs: bug 188
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/industries/systems-integration-technology
- After: https://100434-100726-calendar-update--accenture-newsroom--hlxsites.hlx.live/industries/systems-integration-technology
=> Calendar Filter Year and Popup Fixes

tools/sidekick/config.json
Need this to work on tagger locally
=> adding tagger button (only) to sidekick

blocks/footer/footer.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/241
- https://github.com/hlxsites/accenture-newsroom/issues/241
Test URLs:
- After: https://161108-Tooltip-fr--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Add title attribute geo mapping

tools/importer/import.js
Import script updated
Fix #62 
Test URLs:
- After: https://import-script-updates--accenture-newsroom--hlxsites.hlx.page/
=> Import script updates

fstab.yaml
Fix #<gh-issue-id>
Test URLs:
- After: https://main--accenture-newsroom--hlxsites.hlx.page/
=> pointing path to en

blocks/home-hero/home-hero.css
Fix #271 
Test URLs:
- After: https://143106-149587-hero-heading--accenture-newsroom--hlxsites.hlx.page/
=> Fix: 149587: word wrap fix

README.md
Fix https://github.com/hlxsites/accenture-newsroom/issues/273
- https://github.com/hlxsites/accenture-newsroom/issues/273
Test URLs:
- After: https://182119-Readme--accenture-newsroom--hlxsites.hlx.page/
=> Update: remove environment newsroom links

blocks/header/header.js, blocks/newslist/newslist.js
Fix - nav id and annotations in newslist
Test URLs:
- After: https://analytics-fixes-v3--accenture-newsroom--hlxsites.hlx.page/
=> fix: nav id and annotations in newslist

blocks/newslist/newslist.css
Fix #199 
Test URLs:
- After: https://filter-styling--accenture-newsroom--hlxsites.hlx.page/
=> fix: filter styling for long values in languages like de

blocks/newslist/newslist.css
Fix Newslist search widget in jp site
Test URLs:
- After: https://newslist-search-styling--accenture-newsroom--hlxsites.hlx.page/
=> fix: newslist search styling

tools/importer/import.js
Fix #296 
Test URLs:
- After: https://lang-pages-import--accenture-newsroom--hlxsites.hlx.page/
=> fix: using the original filename and updating category pages

blocks/newslist/newslist.css
Fix #187 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/search
- After: https://73355-result-for-label--accenture-newsroom--hlxsites.hlx.live/search
=> 73355-search result label and count alignment fix

blocks/home-hero/home-hero.css, blocks/newslist/newslist.css
Fix #264 
Test URLs:
- After: https://150296-readmore-cta--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Camelcase Read More CTA for local geos

blocks/video/video.js, scripts/csp.json, tools/importer/import.js
Fix #304 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/drafts/ravi/release-20220427-2
- After: https://youtubevideo--accenture-newsroom--hlxsites.hlx.page/drafts/ravi/release-20220427-2
- After: https://youtubevideo--accenture-newsroom--hlxsites.hlx.page/drafts/ravi/accenture-interactive-expands-experience-led-transformation-services-in-southeast-asia-with-acquisition-award-winning-agency-entropia
=> feat: youtube vidoe embed support

blocks/newslist/newslist.js
Fix #292 
Test URLs:
- After: https://readmmore-fix--accenture-newsroom--hlxsites.hlx.page/
=> fix: read more data-analytics-link-name

tools/sidekick/config.json
Test URLs:
- After: https://enable-draft-publishing--accenture-newsroom--hlxsites.hlx.page/
=> enable draft publishing

blocks/newslist/newslist.css, blocks/newslist/newslist.js
Fix #158 
Test URLs:
- After: https://96065-filter-date-placeholder--accenture-newsroom--hlxsites.hlx.live/
=> 96065 - filter date placeholder fix

blocks/aside/aside.js, blocks/newslist/newslist.js
Fix #324 
Fix #320 
Test URLs:
- After: https://tag-fix--accenture-newsroom--hlxsites.hlx.live/search
- After: https://tag-fix--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-supports-largest-migration-of-electronic-medical-record-system-to-microsoft-azure
=> fix: search analytics name and tag href

blocks/aside/aside.js
Fix #222 
Test URLs:
- After: https://222-it-tags-fix--accenture-newsroom--hlxsites.hlx.page/
=> fixing tag path for IT site

scripts/delayed.js, scripts/scripts.js
Fix #322
Fix #336 
Test URLs:
- After: https://analytics-data-attr--accenture-newsroom--hlxsites.hlx.page/
=> Analytics data attr

tools/importer/import.js
This will fix the import script that adds a space after ---.
One more step is to actually rerun the import again for the news articles.
Fix #341 
Test URLs:
- After: https://fix-extra-spaces--accenture-newsroom--hlxsites.hlx.page/
=> fix extra spaces around the section during import

blocks/footer/footer.css
Fix #337 
Test URLs:
- After: https://282774-footer--accenture-newsroom--hlxsites.hlx.page/
=> Fix two column in sub footer in medium device

scripts/csp.json, scripts/delayed.js
Fix #342 
Test URLs:
- After: https://demandbase--accenture-newsroom--hlxsites.hlx.live/
=> Add demandbase tag

blocks/hero/hero.css
Fix #353
Test URLs:
- After: https://311084-hero-alignment--accenture-newsroom--hlxsites.hlx.page/
=> adjust hero aligment

blocks/home-hero/home-hero.css
Fix https://github.com/hlxsites/accenture-newsroom/issues/351
- https://github.com/hlxsites/accenture-newsroom/issues/351
Test URLs:
- After: https://310989-Hero--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Add overflow hidden to the home-hero

blocks/home-hero/home-hero.css
Fix https://github.com/hlxsites/accenture-newsroom/issues/372
Test URLs:
- After: https://212248-Stripe--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Update hero stripe height

blocks/newslist/newslist.css, blocks/newslist/newslist.js
Fix #365 
Test URLs:
- After: https://filter-styling-tablet--accenture-newsroom--hlxsites.hlx.live/
- After: https://filter-styling-tablet--accenture-newsroom--hlxsites.hlx.live/subjects/technology
=> fix: styling filter widget in tablet view port

styles/styles.css
Fix #356 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds
- After: https://article-styling--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds
=> fix: adding support for center aligning h6

tools/importer/import.js
Fix added support for finding abstract for new patterns in articles
Test URLs:
- After: https://import-abstract-fixes--accenture-newsroom--hlxsites.hlx.live/
=> fix: Import abstract for new patterns

scripts/scripts.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/377
- https://github.com/hlxsites/accenture-newsroom/issues/377
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-reports-fourth-quarter-and-strong-full-year-fiscal-2023-results
- After: https://332119-pdf-link--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-reports-fourth-quarter-and-strong-full-year-fiscal-2023-results
=> Fix: Add target _blank to the PDF links

styles/styles.css
Fix https://github.com/hlxsites/accenture-newsroom/issues/358
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/earnings-infographics
- After: https://311529-Image--accenture-newsroom--hlxsites.hlx.page/earnings-infographics
=> Fix: Update to 100% image width as default

styles/styles.css
Fix Add styles for the download button
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2015/accenture-reports-very-strong-fourth-quarter-and-full-year-fiscal-2015-results
- After: https://download-btn--accenture-newsroom--hlxsites.hlx.live/news/2015/accenture-reports-very-strong-fourth-quarter-and-full-year-fiscal-2015-results
=> fix: download button styles

blocks/table/table.css, blocks/table/table.js, styles/styles.css
Fix #357 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/fact-sheet
- After: https://table--accenture-newsroom--hlxsites.hlx.live/fact-sheet
=> feat: table block

scripts/scripts.js, styles/styles.css
Fix #403 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-expands-strategy-capabilities-in-life-sciences-with-the-acquisition-of-bionest
- After: https://article-previous--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-expands-strategy-capabilities-in-life-sciences-with-the-acquisition-of-bionest
=> fix: article previous button not clickable

blocks/table/table.css
Fix #360
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/fact-sheet
- After: https://table-nobordered--accenture-newsroom--hlxsites.hlx.live/fact-sheet
=> fix: table nobordered vertical alignment

404.html, blocks/newslist/newslist.css
Fix #201 
Test URLs:
- After: https://404-placeholders--accenture-newsroom--hlxsites.hlx.live/
=> fix: use placeholders for messages in 404 page

blocks/table/table.css, blocks/table/table.js
Fix: styling the table bordered variant
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2001/accenture-reports-strong-fourth-quarter-and-year-end-results
- After: https://table-bordered--accenture-newsroom--hlxsites.hlx.live/news/2001/accenture-reports-strong-fourth-quarter-and-year-end-results
=> fix: styling table bordered variant

tools/sidekick/config.json, tools/sidekick/library.html
Fix #412 
Test URLs:
- After: https://library--accenture-newsroom--hlxsites.hlx.live/
=> feat: adding block library picker

blocks/newslist/newslist.js
Fix #420 
Test URLs:
- After: https://accessibility-improvement--accenture-newsroom--hlxsites.hlx.live/
=> accessibility fix

blocks/newslist/newslist.css, scripts/scripts.js
Fix Improving LHS for mobile
Test URLs:
- After: https://lhs--accenture-newsroom--hlxsites.hlx.live/
=> fix: moving calendar widget to semi delayed from lazy loading to improve LHS

blocks/header/header.js, blocks/newslist/newslist.css, blocks/newslist/newslist.js
Fix Below Accessibility issues
Test URLs:
- After: https://aria-nav--accenture-newsroom--hlxsites.hlx.page/
=> fix: a11y issues in nav and newslist

blocks/home-hero/home-hero.js, blocks/newslist/newslist.js, styles/styles.css
Fix 
Test URLs:
- After: https://seo--accenture-newsroom--hlxsites.hlx.live/
=> fix: adding screen reader hints for generic read more texts

tools/importer/import.js
Fix the order of finding the next br node and also the importing of tables
Test URLs:
- After: https://import-fix-order--accenture-newsroom--hlxsites.hlx.live/
=> fix: finding the next br or p node order in import script

blocks/video/video.css
Fix #
There's a request to update the video aspect ratio to 21 / 9 to remove the large white space at the bottom of the video.
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-invests-in-vu-technologies-to-help-companies-use-virtual-production-to-create-new-immersive-experiences
- After: https://video-aspect-ratio--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-invests-in-vu-technologies-to-help-companies-use-virtual-production-to-create-new-immersive-experiences
=> Video aspect ratio

scripts/scripts.js
@michaelktiufb One change to the original issue. the confirmation text I put in says "Are you sure you want to publish this content live?" instead of "Are you sure you want to publish?" just to indicate what publish really means. Easy enough to change the text if this is not good.
Fix #453 
When you click the publish button, a confirmation pops up asking you "Are you sure you want to publish this content live?" and if you click cancel it will not do anything.
Test URLs:
- After: https://publish-confirm--accenture-newsroom--hlxsites.hlx.live/
=> Publish confirm

scripts/scripts.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/453
- https://github.com/hlxsites/accenture-newsroom/issues/453
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/peugeot-appoints-accenture-song-as-global-creative-agency-of-record
- After: https://publishing-pop-up--accenture-newsroom--hlxsites.hlx.page/news/2023/peugeot-appoints-accenture-song-as-global-creative-agency-of-record
=> Fix: Add observer for the helix-sidekick element for Publishing confirmation

blocks/home-hero/home-hero.css, blocks/home-hero/home-hero.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/483
- https://github.com/hlxsites/accenture-newsroom/issues/483
Test URLs:
- After: https://sub-nav-divider--accenture-newsroom--hlxsites.hlx.page/
=> Fix: modify sub nav divider and center aligned

scripts/constants.js
Fix #471
Test URLs:
- After: https://382946-consent-manager--accenture-newsroom--hlxsites.hlx.page/
=> Update: Value of consent manager template zone

scripts/ffetch.js
@amol-anand  @ravkiran  Requesting for your review if the 500 chunk size is just fine
Fix https://github.com/hlxsites/accenture-newsroom/issues/480
https://chunk-size--accenture-newsroom--hlxsites.hlx.live/search?q=Carlyle
https://newsroom.accenture.com/search?q=Carlyle
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/search
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/search
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/search
- After: https://chunk-size--accenture-newsroom--hlxsites.hlx.page/search
- After: https://chunk-size--accenture-newsroom--hlxsites.hlx.page/search
- After: …
=> Update: Chunksize from 255 to 500

styles/styles.css
Fix  https://github.com/hlxsites/accenture-newsroom/issues/488
- https://github.com/hlxsites/accenture-newsroom/issues/488
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-and-google-cloud-launch-joint-generative-ai-center-of-excellence-to-help-enterprises-harness-the-value-of-generative-ai
- After: https://bold-text--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-and-google-cloud-launch-joint-generative-ai-center-of-excellence-to-help-enterprises-harness-the-value-of-generative-ai
=> Fix: Enable bold text for Mac

scripts/delayed.js, scripts/one-trust-geo-script.js, scripts/scripts.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/495
- https://github.com/hlxsites/accenture-newsroom/issues/495
Test URLs:
- After: https://load-beacon--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Implement sat_track script and refactor launch script flow

styles/styles.css
Fix #492 
Test URLs:
- Test Page:https://main--accenture-newsroom--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks
- After: https://450157-sidekick-tools--accenture-newsroom--hlxsites.hlx.page/
=> Update: Add styling for metadata table in sidekick tool bar

blocks/footer/footer.js
Fix #490 
Test URLs:
- After: https://284945-analytics-fr--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Contact-us analytics value for local geo FR

scripts/cookies.js, scripts/delayed.js
Fix https://github.com/hlxsites/accenture-newsroom/issues/503 https://github.com/hlxsites/accenture-newsroom/issues/505 https://github.com/hlxsites/accenture-newsroom/issues/504
- https://github.com/hlxsites/accenture-newsroom/issues/503
- https://github.com/hlxsites/accenture-newsroom/issues/504
- https://github.com/hlxsites/accenture-newsroom/issues/505
Test URLs:
- After: https://minimize-banner--accenture-newsroom--hlxsites.hlx.page/
=> Fix: Onetrust cookie and minimize banner bug

scripts/delayed.js
Fix: Update PT geo One Trust ID
Test URLs:
- After: https://pt-onetrust--accenture-newsroom--hlxsites.hlx.page/
=> update PT Onetrust ID

blocks/aside/aside.css, blocks/aside/aside.js, scripts/constants.js, scripts/scripts.js, tools/tagger/tagger.js
Aside component tags will now validated based on the authored tag values on "tag.xlxs"
Fix https://github.com/hlxsites/accenture-newsroom/issues/497 https://github.com/hlxsites/accenture-newsroom/issues/496
- https://github.com/hlxsites/accenture-newsroom/issues/496
- https://github.com/hlxsites/accenture-newsroom/issues/497
Test URLs:
- After: https://invalid-tag--accenture-newsroom--hlxsites.hlx.page/
=> Implement tag validation and publishing confirmation

scripts/scripts.js
Fix 
Test URLs:
- After: https://sk-observer--accenture-newsroom--hlxsites.hlx.page/
=> Moved helixSideKickObserver

scripts/scripts.js
Fix 
Test URLs:
- After: https://sk-publish--accenture-newsroom--hlxsites.hlx.page/
=> update publish confirmation

scripts/scripts.js
Fix #517 
Test URLs:
- After: https://analytics-csp-v2--accenture-newsroom--hlxsites.hlx.page/
=> Update: Add condition in using csp.js file in prod

blocks/aside/aside.css, blocks/aside/aside.js, scripts/constants.js, scripts/scripts.js, tools/tagger/tagger.js
Fix #
Test URLs:
- After: https://pub-later-dev--accenture-newsroom--hlxsites.hlx.page/
=> Get the latest from the main branch

blocks/aside/aside.css, blocks/aside/aside.js, scripts/constants.js, scripts/scripts.js, tools/tagger/tagger.js
Reverts hlxsites/accenture-newsroom#522
Test URLs:
Before: https://main--accenture-newsroom--hlxsites.hlx.page/
After: https://pub-later-dev--accenture-newsroom--hlxsites.hlx.page/
After: https://revert-522-main--accenture-newsroom--hlxsites.hlx.page/
=> Revert "Get the latest from the main branch"

tools/metadata/index.html, tools/metadata/metadata.css, tools/metadata/metadata.js, tools/sidekick/config.json
Fix #520 
- Fix label translation of metadata helper
- Fix Publish date translation base on specific geo
- Add checkbox in Category
Test URLs:
- After: https://medata-tools--accenture-newsroom--hlxsites.hlx.page/
=> Metadata Helper Tool Enhancement
