helix-query.yaml

Fix Query Index definition
Added 
- `publisheddateinseconds` - shows the published date in seconds
- `longdescriptionextracted` - first section content in main
The order of the usage will be like this (will be done in separate PR, once this is merged)
- The largest of `description` and `longdescriptionextracted`, this way we'll show something that's meaningful, rather than showing some weird characters.
Test URLs:
- After: https://query-index--accenture-newsroom--hlxsites.hlx.page/

fix: query index definition

---

blocks/hero/hero.css

Fix: article hero coming on top of the header
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
- After: https://header-fix--accenture-newsroom--hlxsites.hlx.page/news/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture

fix: article hero showing on top of header

---

blocks/aside/aside.js

Fix https://github.com/hlxsites/accenture-newsroom/issues/133
- https://github.com/hlxsites/accenture-newsroom/issues/133
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-completes-acquisition-of-anser-advisory
- After: https://84836-PDF-Links--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-completes-acquisition-of-anser-advisory

Fix: Convert anchor tag to text node before generating PDF

---

blocks/home-hero/home-hero.css

Fix https://github.com/hlxsites/accenture-newsroom/issues/149
- https://github.com/hlxsites/accenture-newsroom/issues/149
- need to update the authoring of card title and add link to it. I attached my demo testpage and add link to the card title then css will remove the arrow and color of it to make it look the same with the legacy page.
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/drafts/jaspher/demo
- After: https://85035-hero-title--accenture-newsroom--hlxsites.hlx.page/drafts/jaspher/demo
- After: https://85035-hero-title--accenture-newsroom--hlxsites.hlx.page/

Fix: add styling to Home hero card title link

---

blocks/newslist/newslist.js

Fix https://github.com/hlxsites/accenture-newsroom/issues/216
- https://github.com/hlxsites/accenture-newsroom/issues/216
Test URLs:
- After: https://143053-br-newscard--accenture-newsroom--hlxsites.hlx.page/
it seems this part of the code was deleted. 
https://github.com/hlxsites/accenture-newsroom/pull/130#discussion_r1334747190

Fix: Remove first br tag for the news card

---

blocks/newslist/newslist.js

Fix https://github.com/hlxsites/accenture-newsroom/issues/224
- https://github.com/hlxsites/accenture-newsroom/issues/224
Test URLs:
- Before: https://main--accenture-newsroom-jp--hlxsites.hlx.page/
- After: https://149585-newsfeed--accenture-newsroom--hlxsites.hlx.page/
- After: https://149585-newsfeed--accenture-newsroom-jp--hlxsites.hlx.page/
there's a console error for some geos caused by undefined matchingParagraph querySelector br element,
Fix: Add null check to  matchingParagraph before querySector of br element
Local JP geo

Fix: add null check to the matchingParagraph variable

---

tools/sidekick/config.json
tools/tagger/index.html
tools/tagger/tagger.css
tools/tagger/tagger.js

Adding tagger functionality to show up during editing.
It reads from /tags.json (tags is an excel file with subjects and industries as two columns)
Fix #15 
No before/after since this is sidekick functionality.
See screenshot of working tagger below:

Sidekick tagger

---

tools/importer/import.js

Fix: industry and subjects tag
Test URLs:
- After: https://import-tags--accenture-newsroom--hlxsites.hlx.page/

fix: using the tag links rather than text to import subjects and industries tags

---

blocks/aside/aside.js

**Please remember** to re-import the language sites after merging https://github.com/hlxsites/accenture-newsroom/pull/278. This current PR uses the tag format imported in https://github.com/hlxsites/accenture-newsroom/pull/278
Fix #222 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/drafts/ravi/accenture-song-wins-dan-wieden-titanium-grand-prix-for-tuvalu-the-first-digital-nation
- After: https://tag-translation--accenture-newsroom--hlxsites.hlx.page/drafts/ravi/accenture-song-wins-dan-wieden-titanium-grand-prix-for-tuvalu-the-first-digital-nation

fix: using translations for tags

---

scripts/csp.json

adding some more domains that were missing the first time
Fix #257 
Test URLs:
- After: https://csp-updates--accenture-newsroom--hlxsites.hlx.page/

updating csp list

---

tools/importer/import.js

Fix the category page import to use tag name instead of title
Test URLs:
- After: https://import-category-pages--accenture-newsroom--hlxsites.hlx.page/

fix: updating the category page import to use the tag name instead of title

---

blocks/newslist/newslist.js
scripts/scripts.js

Fix the date translation in local geo <BR>. Remove the extra word (DE) in the translation.
Fix #239 
Test URLs:
- After: https://149669-date-trans--accenture-newsroom--hlxsites.hlx.page/

149669 date trans

---

blocks/aside/aside.js
blocks/newslist/newslist.js
scripts/scripts.js
tools/importer/import.js

Fix accented characters in subjects/industries
Test URLs:
- After: https://tags-accented--accenture-newsroom--hlxsites.hlx.live/subjects/supply-chain-management
- After: https://tags-accented--accenture-newsroom--hlxsites.hlx.live/
- After: https://tags-accented--accenture-newsroom--hlxsites.hlx.live/news/2023/three-in-four-semiconductor-executives-expect-supply-chain-challenges-to-ease-by-2024-accenture-report-finds

fix: accented characters in subjects/industries

---

blocks/aside/aside.js

Fix #222 
Test URLs:
- After: https://tag-path--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-federal-services-wins-position-on-irs-blanket-purchase-agreement-with-2-6-b-ceiling-value

fix: tag path prefix based on site name

---

scripts/scripts.js
styles/styles.css

Fix #368
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live//news/2023/accenture-reports-strong-third-quarter-fiscal-2023-results
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-federal-services-and-google-public-sector-launch-cybersecurity-center-of-excellence
- After: https://aside-height--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-reports-strong-third-quarter-fiscal-2023-results
- After: https://aside-height--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-federal-services-and-google-public-sector-launch-cybersecurity-center-of-excellence

fix: aside height to fully show the aside container

---

blocks/aside/aside.js

Fix #354 
Test URLs:
- After: https://pdf-new-tab--accenture-newsroom--hlxsites.hlx.page/

open pdf in new tab instead of save by default

---

scripts/scripts.js
styles/styles.css

Fix - assume the first section as abstract rather than matching with regex to find the abstract, given that we've imported the abstract for most of the articles.
Test URLs:
- After: https://simplify-abstract--accenture-newsroom--hlxsites.hlx.live/
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/ceos-lack-confidence-in-their-organizations-ability-to-protect-against-cyberattacks-despite-seeing-cybersecurity-as-vital-to-growth-accenture-report-finds
- After: https://simplify-abstract--accenture-newsroom--hlxsites.hlx.live/news/2023/ceos-lack-confidence-in-their-organizations-ability-to-protect-against-cyberattacks-despite-seeing-cybersecurity-as-vital-to-growth-accenture-report-finds
cc: @raymond-h-dev …

fix: assume that first section in the doc is abstract

---

blocks/aside/aside.js

Reverts hlxsites/accenture-newsroom#371
https://github.com/hlxsites/accenture-newsroom/issues/354
Hi @amol-anand @ravkiran , there was a confusion with this bug https://github.com/hlxsites/accenture-newsroom/issues/354 and IIiyaz and Eula is asking to revert this changes.

Revert "open pdf in new tab instead of save by default"

---

styles/styles.css

Fix #359 
Fix #361 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-invests-in-looking-glass-to-accelerate-shift-from-2d-to-3d
- After: https://article-captions--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-invests-in-looking-glass-to-accelerate-shift-from-2d-to-3d
- After: https://article-captions--accenture-newsroom--hlxsites.hlx.live/news/2023/growing-consumer-and-business-interest-in-the-metaverse-expected-to-fuel-trillion-dollar-opportunity-for-commerce-accenture-finds

fix: captions styling in article

---

blocks/home-hero/home-hero.css

Business for this is to remove the arrow in all geos.
Fix #362 
Test URLs:
- After: https://multinav-arrow--accenture-newsroom--hlxsites.hlx.page/

remove the arrow in multinav

---

scripts/lib-franklin.js

Fix Don't style mailto links as buttons
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2013/accenture-and-the-challenged-athletes-foundation-to-support-injured-troops-at-ironman-70-3-california
- After: https://button-style--accenture-newsroom--hlxsites.hlx.live/news/2013/accenture-and-the-challenged-athletes-foundation-to-support-injured-troops-at-ironman-70-3-california

fix: don't style mailto links as buttons

---

styles/styles.css

Fix styling mailto a tags
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2012/united-bank-of-india-awards-accenture-two-year-management-consulting-agreement-to-support-its-strategic-transformation-program
- After: https://mailto--accenture-newsroom--hlxsites.hlx.live/news/2012/united-bank-of-india-awards-accenture-two-year-management-consulting-agreement-to-support-its-strategic-transformation-program

fix: styling mailto a tags

---

styles/styles.css

Fix applying article h1 styling to h2 and h3 as well to fix the headings in geo sites
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-collaborates-with-sap-to-help-organizations-adopt-generative-ai-and-accelerate-erp-transformation-in-the-cloud
- After: https://heading-styling--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-collaborates-with-sap-to-help-organizations-adopt-generative-ai-and-accelerate-erp-transformation-in-the-cloud

fix: applying article h1 styling to h2 and h3 as well

---

blocks/newslist/newslist.js

Fix 
If the regex match is not found, currently we're only showing the title, this is happening more in geo sites
This fix will use the abstract by cleaning up headings in case the regex match not found
Please check on https://description-update--accenture-newsroom--hlxsites.hlx.live?page=524
Test URLs:
- After: https://description-update--accenture-newsroom--hlxsites.hlx.live/

fix: use the abstract for description when regex match not found

---

blocks/home-hero/home-hero.css

Fix https://github.com/hlxsites/accenture-newsroom/issues/417
- https://github.com/hlxsites/accenture-newsroom/issues/417
Test URLs:
- After: https://home-hero-cta--accenture-newsroom--hlxsites.hlx.page/

Fix: Revert the arrow icon for the home hero cta

---

404.html

Fix https://github.com/hlxsites/accenture-newsroom/issues/430
- https://github.com/hlxsites/accenture-newsroom/issues/430
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/123
- After: https://123708-pnf-message--accenture-newsroom--hlxsites.hlx.page/123
I also updated the pageNotFoundMessage placeholder and add new placeholder "Search Functionality" for the translation use case when implemented to the other local geo in the future.

Fix: Add hyperlink search functionality to the page not found message

---

scripts/scripts.js

Fix https://github.com/hlxsites/accenture-newsroom/issues/433
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-reports-fourth-quarter-and-strong-full-year-fiscal-2023-results
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/earnings-infographics
- After: https://inline-pdf-link--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-reports-fourth-quarter-and-strong-full-year-fiscal-2023-results
- After: https://inline-pdf-link--accenture-newsroom--hlxsites.hlx.page/earnings-infographics

Fix: Implement pdfLinkHandler regardless of the template

---

blocks/newslist/newslist.js

Fix SEO score
Test URLs:
- After: https://seo-pagination--accenture-newsroom--hlxsites.hlx.live/

fix: adding href for disabled arrows in pagination for improving SEO score

---

tools/tagger/tagger.js

- Fix value the tagger after copying instead of "Talent & Organization Performance, Aerospace & Defense" to "talent-organization-performance, aerospace-defense"
- Fix the issue of not enable copy button after the clicking clear or selecting new tag.
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/tools/tagger/index.html
- After: https://373898-tagger--accenture-newsroom--hlxsites.hlx.page/tools/tagger/index.html
cc: @raymond-h-dev @jjjaspher

Fix tagger value after clicking copy button in tagger tool

---

scripts/scripts.js

Fix Removing the word boundaries restriction from abstract regex
https://newsroom.accenturebr.com/br/news/2022/estrategia-de-tecnologia-sustentavel-e-fundamental-para-alcancar-crescimento-dos-negocios-e-desempenho-esg
The lang characters in the string 
```
NOVA YORK, 6 de julho de 2022 – À medida que as empresas definem metas ambientais, sociais e de governança (ESG, em inglês) cada vez mais ambiciosas, suas estratégias de sustentabilidade e tecnologia precisam estar alinhadas para garantir vantagem competitiva, valor financeiro e um impacto positivo duradouro na sociedade e no meio ambiente. É o que mostra o novo levantamento conduzido pela …
```

fix: removing word boundaries from abstract finding regex

---

scripts/scripts.js
styles/styles.css

Issue: A.com search page aren't able to search our newsroom pages.
As per discussion to with @raymond-h-dev, as part of resolution. We need to update the article date "p" tag element to "div" element. If no date on the article page then we need to create hidden div date element based from the metadata published date and make it hidden.
Fix 
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-solnet-to-expand-cloud-first-capabilities-in-aotearoa-new-zealand
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2000/accenture-and-asera-inc-team-to-provideinternet-based-b …

Refactor: Convert article date p tag to div tag

---

blocks/aside/aside.js

Implement the newer version of twitter share
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview
Fix https://github.com/hlxsites/accenture-newsroom/issues/456
- https://github.com/hlxsites/accenture-newsroom/issues/456
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-and-avanade-expand-capabilities-to-accelerate-data-readiness-and-generative-ai-adoption-with-microsoft-technology
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-and-avanade-expand-capabilities-to-accelerate-data-readiness-and-generative-ai-adoption-with-microsoft-technology
- …

Fix: Update the twitter share url

---

scripts/scripts.js
styles/styles.css

Reverts hlxsites/accenture-newsroom#455
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-solnet-to-expand-cloud-first-capabilities-in-aotearoa-new-zealand
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2000/accenture-and-asera-inc-team-to-provideinternet-based-business-to-business-demand-chain-solutions
- After: https://revert-455-article-date-el--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-solnet-to-expand-cloud-first-capabilities-in-aotearoa-new-zealand
- After: https://revert-455-article-date-el--accenture-newsroom--hlxsites.hlx.live/news/2000/accenture-and-asera-inc-team-to-provideinternet-based-business-to-business-demand-chain-solutions

Revert "Refactor: Convert article date p tag to div tag"

---

tools/sidekick/config.json

Fix 401 issue while accessing tagger and block library.
**Requests to static html pages do not go through the pipeline as of today, so tagger and block library isn't showing the auth. I've added redirects for tagger and library so that these are handled by the pipeline and show the authentication.**
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/tools/sidekick/library
- After: https://tools-auth--accenture-newsroom--hlxsites.hlx.page/tools/sidekick/library
- After: https://tools-auth--accenture-newsroom--hlxsites.hlx.page/tools/tagger

fix: using redirect for tagger and library for avoiding the 401 and showing the auth

---

styles/styles.css

Fix #485
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/finnish-defence-forces-to-collaborate-with-accenture-on-an-enterprise-resource-planning-transformation-programme-based-on-sap-hana
- After: https://titlestyling--accenture-newsroom--hlxsites.hlx.live/news/2023/finnish-defence-forces-to-collaborate-with-accenture-on-an-enterprise-resource-planning-transformation-programme-based-on-sap-hana

fix: use semibold font for h1/h2/h3 and strong tags

---

scripts/scripts.js

Implemented the sidekick-ready event as per suggestion of @ravkiran 
https://github.com/hlxsites/accenture-newsroom/pull/481#discussion_r1421837904
Fix https://github.com/hlxsites/accenture-newsroom/issues/453
- https://github.com/hlxsites/accenture-newsroom/issues/453
Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/peugeot-appoints-accenture-song-as-global-creative-agency-of-record
- After: https://publishing-pop-up--accenture-newsroom--hlxsites.hlx.page/news/2023/peugeot-appoints-accenture-song-as-global-creative-agency-of-record

Refactor: Implement sidekick-ready event for publish confirmation

---

blocks/newslist/newslist.js
scripts/scripts.js

Fix #529 https://github.com/hlxsites/accenture-newsroom/issues/529
Test URLs:
- After: https://calendar-filter--accenture-newsroom--hlxsites.hlx.page/

Fix: Calendar filter input must not query future dates
